finish view
Mylo16/blogapp pull request #6
Opened 2023-07-27 22:34 UTC by Mylo16

### In this PR:
- I created view actions for my blogapp
- I made use of partials to make my code DRY
- I implemented navigation between different views
- I followed Ruby's best practices
- There are no linter errors

2023-07-27 22:52 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Mylo16,

### Nice job, you are almost there.

![giphy (2)](https://user-images.githubusercontent.com/68796232/223284713-d4ea97f0-5ad2-438b-8ac5-1481a991da3f.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔
- You used partials correctly. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- [ ] Please check the inline comments below ⬇️.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-07-27 22:52 UTC, Omar-Muhamad commented on app/views/users/index.html.erb
> +    </a>
- [ ] [Optional] It would be much better if you used the `link_to` method instead of the regular anchor `<a>` tag. See [this ](https://www.rubyguides.com/2019/05/rails-link_to-method/)for more info.

2023-07-27 22:52 UTC, Omar-Muhamad commented on app/views/users/index.html.erb
> +    </a>
- [ ] Good job using partials for repeatable blocks of code 👍.

2023-07-27 22:52 UTC, Omar-Muhamad commented on app/views/users/show.html.erb
> +  <a href= <%= user_posts_path(user_id: @user.id) %> class="see-posts">See all posts</a>
- [ ] [Optional] Same here, It would be much better if you used the `link_to` method instead of the regular anchor `<a>` tag. See [this ](https://www.rubyguides.com/2019/05/rails-link_to-method/)for more info.

2023-07-27 22:52 UTC, Omar-Muhamad commented on app/views/users/show.html.erb
> +  <% @user.posts.each_with_index do |post, index| %>
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md#:~:text=page%20to%20another-,Use%20methods%20that%20you%20have%20created%20in%20the%20Blog%20App%20%2D%20processing%20data%20in%20models.,-Hint%3A%20In), Please use the `recent_posts` method from user model to render the 3 most recent posts only, not all posts as you did here.

2023-07-27 22:52 UTC, Omar-Muhamad commented on app/views/posts/index.html.erb
> +      <% end %>
- [ ] Same here, As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md#:~:text=page%20to%20another-,Use%20methods%20that%20you%20have%20created%20in%20the%20Blog%20App%20%2D%20processing%20data%20in%20models.,-Hint%3A%20In), Please use the `recent_comments` method from post model here to render the 5 most recent comments only, not all comments as you did here.

2023-07-27 22:52 UTC, Omar-Muhamad commented on app/views/posts/index.html.erb
> +    <a class="post-card-container2" href=<%= user_post_path(@user, post) %>><%= render partial: "shared/post_card", locals: { post: post, index: index + 1 } %></a>
- [ ] [Optional] It would be much better if you used the `link_to` method instead of the regular anchor `<a>` tag. See [this ](https://www.rubyguides.com/2019/05/rails-link_to-method/)for more info.

2023-07-28 11:36 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

### Hey @Mylo16 👋

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following Requirements
✔️ Great work on using the models' methods 👍
✔️ Great work on using reusable partials 🔥

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 11:36 UTC, HAMMAS-SALEEM commented on app/views/users/index.html.erb
>  <h1>All Users</h1>
![image](https://github.com/Mylo16/blogapp/assets/93039359/87c9e1fe-f184-46c4-bc23-38cb72a02755)

**[OPTIONAL]**

- [ ] It would be nice if your app show the real image of the user because I have given it the URL to my image but I can't see my image as you can see in the screenshot above :arrow_up: Kindly fix this Issue to make your app more professional and give a great user experience :+1:

2023-07-28 12:21 UTC, merged