finish integration specs and n+1 queries problem solution
Mylo16/blogapp pull request #8
Opened 2023-08-01 18:11 UTC by Mylo16

### In this PR:
- I created integration spec to test for the views of the app
- I implemented includes method to solve n + 1 query problems. The results are attached below.
- I followed Ruby's best practices
- There are no linter errors

Before:
![before_includes](https://github.com/Mylo16/blogapp/assets/112702953/9f0f11ec-48b5-41c7-b954-0777ae023836)

After:
![after_include_posts](https://github.com/Mylo16/blogapp/assets/112702953/51f6f81c-704f-41a0-8ca8-ac025ddc20c8)

2023-08-01 18:21 UTC, HAMMAS-SALEEM reviewed
# Invalid Submission :red_circle:

![invalid-submission](https://user-images.githubusercontent.com/93039359/221218445-05489541-f840-492c-878e-0587cc2b3702.gif)

## Hey @Mylo16 :wave:

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 18:21 UTC, HAMMAS-SALEEM commented on app/controllers/posts_controller.rb
- [ ] It would be nice if your partner should commit to this pull request since it is a pair-programming activity 👍 If you don't have any partner then kindly pin a screenshot of your dashboard and a screenshot of the email from microverse (If you had a partner but you get separated) in the pull request summary so the next reviewer won't invalidate your pull request 😊

2023-08-02 12:35 UTC, julie-ify reviewed
Hi @Mylo16 and @naanmohammed,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* The other coding partner only updated the readme file. Kindly note that this is not a valid contribution. Everyone on the team must contribute actual code.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-02 18:19 UTC, ishimwezachee requested changes
Hi @Mylo16 and @naanmohammed , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif)

## Highlights
✅ test for user index/show were implemented 
✅ test for user post pages were implemented
✅ n+1 problems has been resolved 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 18:19 UTC, ishimwezachee commented on spec/integration/users_index_spec.rb
> +end
- [ ]  This file contain piece of test that is not passing properly due to the typo error, please fix it so that all tests can pass.  Check out the image below to see the error and correct it. 
![image](https://github.com/Mylo16/blogapp/assets/43877689/f725dc29-8edc-4ed0-bb22-e90938ce7b52)

2023-08-02 19:17 UTC, mikethreels approved these changes
Hi Eric, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job following the instructions of the previous CR.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 19:24 UTC, merged